### ISSUE TITLE
Running LOHHLA without "chr6_apd_hap1", "chr6_cox_hap2", "chr6_dbb_hap3"

### ISSUE THREAD

**Issue by ahana706** [ParkerICI/lohhla-container#1]
Hi,
I trying to run LOHHLA for my BAm files which does not have the contigs "chr6_apd_hap1", "chr6_cox_hap2", "chr6_dbb_hap3", "chr6_mann_hap4" and other extra contigs for the chromosome 6. 
 I do have "chr6:29909037-29913661","chr6:31321649-31324964" and "chr6:31236526-31239869"Will I still be able to run LOHHLA?

**Comment by dannykwells** [comment]
Hi @ahana706 I would give it a shot. I honestly don't know. We've been successful running LOHHLA with hg19-aligned exomes.

Note that to run LOHHLA you'll also need a polysolver-style hla as well as a tumor purity and ploidy calls.

**Comment by dannykwells** [comment]
I think so, but to be clear, we do not maintain LOHHLA, only the container.
If you have an question about the tool itself I encourage you to look on
the bitbucket: https://bitbucket.org/mcgranahanlab/lohhla Or email the
maintainer listed there.
